import Foundation
import OSLog
#if os(macOS)
import AppKit
#endif

/// Service for importing and exporting configurations
/// Supports multiple formats: JSON, Surge, etc.
public actor ImportExportService {
    // MARK: - Properties

    private let logger: OSLog
    private let fileManager = FileManager.default

    // MARK: - Initialization

    public init(logger: OSLog? = nil) {
        self.logger = logger ?? OSLog(subsystem: "com.swiftproxy.app", category: "import-export")
    }

    // MARK: - Export

    /// Export configuration to JSON format
    public func exportConfiguration(_ configuration: ProxyConfiguration, to url: URL) async throws {
        os_log(.info, log: logger, "Exporting configuration '\(configuration.name)' to \(url.path)")

        let encoder = JSONEncoder()
        encoder.outputFormatting = [.prettyPrinted, .sortedKeys]
        encoder.dateEncodingStrategy = .iso8601

        let data = try encoder.encode(configuration)

        try data.write(to: url, options: [.atomic])

        os_log(.info, log: logger, "Configuration exported successfully")
    }

    /// Export multiple configurations
    public func exportConfigurations(_ configurations: [ProxyConfiguration], to url: URL) async throws {
        os_log(.info, log: logger, "Exporting \(configurations.count) configurations to \(url.path)")

        let encoder = JSONEncoder()
        encoder.outputFormatting = [.prettyPrinted, .sortedKeys]
        encoder.dateEncodingStrategy = .iso8601

        let data = try encoder.encode(configurations)

        try data.write(to: url, options: [.atomic])

        os_log(.info, log: logger, "Configurations exported successfully")
    }

    /// Export configuration in Surge format
    public func exportConfigurationAsSurge(_ configuration: ProxyConfiguration, to url: URL) async throws {
        os_log(.info, log: logger, "Exporting configuration '\(configuration.name)' as Surge format to \(url.path)")

        var lines: [String] = []

        // Header
        lines.append("[Proxy]")
        lines.append("# Generated by SwiftProxy")
        lines.append("# Configuration: \(configuration.name)")
        lines.append("")

        // Proxy definition
        let proxyType = configuration.type.surgeType
        var proxyLine = "\(configuration.name) = \(proxyType), \(configuration.host), \(configuration.port)"

        if configuration.requiresAuth {
            proxyLine += ", username=\(configuration.username ?? ""), password=\(configuration.password ?? "")"
        }

        if configuration.type == .https {
            proxyLine += ", tls=true"
        }

        lines.append(proxyLine)
        lines.append("")

        // Proxy Group (optional)
        lines.append("[Proxy Group]")
        lines.append("# Add your proxy groups here")
        lines.append("")

        // Rule (optional)
        lines.append("[Rule]")
        lines.append("# Add your rules here")
        lines.append("FINAL,\(configuration.name)")

        let content = lines.joined(separator: "\n")
        try content.write(to: url, atomically: true, encoding: .utf8)

        os_log(.info, log: logger, "Configuration exported as Surge format successfully")
    }

    /// Export all data including configurations, rules, and settings
    public func exportAllData(
        configurations: [ProxyConfiguration],
        rules: [ProxyRule],
        to url: URL
    ) async throws {
        os_log(.info, log: logger, "Exporting all data to \(url.path)")

        let exportData = ExportData(
            version: "1.0",
            exportDate: Date(),
            configurations: configurations,
            rules: rules
        )

        let encoder = JSONEncoder()
        encoder.outputFormatting = [.prettyPrinted, .sortedKeys]
        encoder.dateEncodingStrategy = .iso8601

        let data = try encoder.encode(exportData)

        try data.write(to: url, options: [.atomic])

        os_log(.info, log: logger, "All data exported successfully")
    }

    // MARK: - Import

    /// Import configuration from JSON file
    public func importConfiguration(from url: URL) async throws -> ProxyConfiguration {
        os_log(.info, log: logger, "Importing configuration from \(url.path)")

        let data = try Data(contentsOf: url)

        let decoder = JSONDecoder()
        decoder.dateDecodingStrategy = .iso8601

        let configuration = try decoder.decode(ProxyConfiguration.self, from: data)

        os_log(.info, log: logger, "Configuration '\(configuration.name)' imported successfully")

        return configuration
    }

    /// Import multiple configurations
    public func importConfigurations(from url: URL) async throws -> [ProxyConfiguration] {
        os_log(.info, log: logger, "Importing configurations from \(url.path)")

        let data = try Data(contentsOf: url)

        let decoder = JSONDecoder()
        decoder.dateDecodingStrategy = .iso8601

        let configurations = try decoder.decode([ProxyConfiguration].self, from: data)

        os_log(.info, log: logger, "\(configurations.count) configurations imported successfully")

        return configurations
    }

    /// Import configuration from URL string
    public func importConfigurationFromURL(_ urlString: String) async throws -> ProxyConfiguration {
        os_log(.info, log: logger, "Importing configuration from URL: \(urlString)")

        guard let url = URL(string: urlString) else {
            throw ImportExportError.invalidURL
        }

        let (data, _) = try await URLSession.shared.data(from: url)

        let decoder = JSONDecoder()
        decoder.dateDecodingStrategy = .iso8601

        let configuration = try decoder.decode(ProxyConfiguration.self, from: data)

        os_log(.info, log: logger, "Configuration '\(configuration.name)' imported from URL successfully")

        return configuration
    }

    /// Import configuration from clipboard
    public func importConfigurationFromClipboard() async throws -> ProxyConfiguration {
        os_log(.info, log: logger, "Importing configuration from clipboard")

        guard let clipboardString = await MainActor.run(body: {
            NSPasteboard.general.string(forType: .string)
        }) else {
            throw ImportExportError.emptyClipboard
        }

        guard let data = clipboardString.data(using: .utf8) else {
            throw ImportExportError.invalidData
        }

        let decoder = JSONDecoder()
        decoder.dateDecodingStrategy = .iso8601

        let configuration = try decoder.decode(ProxyConfiguration.self, from: data)

        os_log(.info, log: logger, "Configuration '\(configuration.name)' imported from clipboard successfully")

        return configuration
    }

    /// Import all data from backup file
    public func importAllData(from url: URL) async throws -> ExportData {
        os_log(.info, log: logger, "Importing all data from \(url.path)")

        let data = try Data(contentsOf: url)

        let decoder = JSONDecoder()
        decoder.dateDecodingStrategy = .iso8601

        let exportData = try decoder.decode(ExportData.self, from: data)

        os_log(.info, log: logger, "All data imported successfully: \(exportData.configurations.count) configurations, \(exportData.rules.count) rules")

        return exportData
    }

    /// Parse Surge configuration file
    public func importSurgeConfiguration(from url: URL) async throws -> [ProxyConfiguration] {
        os_log(.info, log: logger, "Importing Surge configuration from \(url.path)")

        let content = try String(contentsOf: url, encoding: .utf8)
        let lines = content.components(separatedBy: .newlines)

        var configurations: [ProxyConfiguration] = []
        var inProxySection = false

        for line in lines {
            let trimmed = line.trimmingCharacters(in: .whitespaces)

            // Skip empty lines and comments
            if trimmed.isEmpty || trimmed.hasPrefix("#") {
                continue
            }

            // Check section
            if trimmed.hasPrefix("[") {
                inProxySection = trimmed.lowercased().contains("[proxy]")
                continue
            }

            // Parse proxy line
            if inProxySection {
                if let config = parseSurgeProxyLine(trimmed) {
                    configurations.append(config)
                }
            }
        }

        os_log(.info, log: logger, "\(configurations.count) configurations imported from Surge file")

        return configurations
    }

    // MARK: - Private Helpers

    private func parseSurgeProxyLine(_ line: String) -> ProxyConfiguration? {
        let components = line.components(separatedBy: ",").map { $0.trimmingCharacters(in: .whitespaces) }

        guard components.count >= 3 else { return nil }

        let nameAndType = components[0].components(separatedBy: "=").map { $0.trimmingCharacters(in: .whitespaces) }
        guard nameAndType.count == 2 else { return nil }

        let name = nameAndType[0]
        let typeString = nameAndType[1].lowercased()
        let host = components[1]

        guard let port = Int(components[2]) else { return nil }

        // Map Surge type to ProxyProtocolType
        let type: ProxyProtocolType
        switch typeString {
        case "http", "https":
            type = typeString == "https" ? .https : .http
        case "socks5", "socks5-tls":
            type = .socks5
        default:
            return nil
        }

        // Parse additional parameters
        var username: String?
        var password: String?

        for component in components.dropFirst(3) {
            let parts = component.components(separatedBy: "=").map { $0.trimmingCharacters(in: .whitespaces) }
            if parts.count == 2 {
                switch parts[0].lowercased() {
                case "username":
                    username = parts[1]
                case "password":
                    password = parts[1]
                default:
                    break
                }
            }
        }

        return ProxyConfiguration(
            name: name,
            type: type,
            host: host,
            port: port,
            requiresAuth: username != nil,
            username: username,
            password: password
        )
    }
}

// MARK: - Supporting Types

public struct ExportData: Codable {
    public let version: String
    public let exportDate: Date
    public let configurations: [ProxyConfiguration]
    public let rules: [ProxyRule]

    public init(version: String, exportDate: Date, configurations: [ProxyConfiguration], rules: [ProxyRule]) {
        self.version = version
        self.exportDate = exportDate
        self.configurations = configurations
        self.rules = rules
    }
}

public enum ImportExportError: LocalizedError {
    case invalidURL
    case invalidData
    case emptyClipboard
    case unsupportedFormat
    case fileNotFound

    public var errorDescription: String? {
        switch self {
        case .invalidURL:
            return "Invalid URL"
        case .invalidData:
            return "Invalid data format"
        case .emptyClipboard:
            return "Clipboard is empty"
        case .unsupportedFormat:
            return "Unsupported file format"
        case .fileNotFound:
            return "File not found"
        }
    }
}

// MARK: - ProxyProtocolType Extension

private extension ProxyProtocolType {
    var surgeType: String {
        switch self {
        case .http:
            return "http"
        case .https:
            return "https"
        case .socks5:
            return "socks5"
        }
    }
}
